package com.regulus.platform.gradle;

import org.gradle.api.DefaultTask;
import org.gradle.api.tasks.TaskAction;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;

public abstract class RegulusComplianceMatrixTask extends DefaultTask {

    @TaskAction
    public void render() throws IOException {
        RegulusComplianceExtension ext = getProject().getExtensions()
                .getByType(RegulusComplianceExtension.class);
        File out = new File(getProject().getRootDir(), ext.getMatrixOutput());
        Files.createDirectories(out.getParentFile().toPath());

        StringBuilder sb = new StringBuilder();
        sb.append("# Regulus Coverage Matrix\n\n");
        sb.append("Generated by `regulusComplianceMatrix`. Source profiles: ")
          .append(ext.getProfiles()).append("\n\n");
        sb.append("| Profile | Mechanism | Clause | Rationale |\n");
        sb.append("|---|---|---|---|\n");
        for (String profileId : ext.getProfiles()) {
            sb.append("| `").append(profileId).append("` | _generated at runtime via ComplianceProfile.controls()_ | | |\n");
        }
        Files.writeString(out.toPath(), sb.toString());

        getLogger().lifecycle("regulusComplianceMatrix: wrote {}", out);
    }
}
